repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files
        entry: actionlint
        language: system
        types: [yaml]
        files: '^\.github/workflows/.*\.(yml|yaml)$'