name: Actionlint

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
  workflow_dispatch:

jobs:
  actionlint:
    name: Check workflow files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
          # Optional: filter mode for reviewdog
          # - "added" (default): only report issues in added/modified lines
          # - "diff_context": report issues in diff context
          # - "file": report all issues in modified files
          # - "nofilter": report all issues in all files
          filter_mode: added
          # Optional: Working directory
          # workdir: ./
          
      - name: Annotate workflow files issues
        if: failure()
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          level: error